
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- .Values.nginx.config | nindent 4 }}